const frac=(a,b)=>`<span class="frac"><span>${a}</span><span>${b}</span></span>`;
export const CHAPTERS=[
{tab:'Две частицы',title:'От двух частиц<br>к одному движению',kicker:'01 / ОТНОСИТЕЛЬНОЕ ДВИЖЕНИЕ',scene:'Что меняется при смене системы отсчёта',defaults:{model:'hs',b:.65,E:1,phi:18,time:.39},steps:[
 {title:'Лабораторная система',text:'<p>Частица 1 налетает на первоначально покоящуюся частицу 2. После удара движутся обе. Меняйте отношение масс: траектории частиц изменяются, но закон относительного движения остаётся тем же.</p>',eq:`<div>m₁v₁ + m₂v₂ = const</div><div class="small">R = ${frac('m₁r₁ + m₂r₂','m₁ + m₂')}</div>`,note:'Нажмите пуск. Белая метка центра масс движется равномерно.'},
 {title:'Система центра масс',text:'<p>Вычитаем скорость центра масс <strong>V</strong> из обеих скоростей. Центр масс теперь неподвижен. В любой момент радиус-векторы частиц направлены противоположно и обратно пропорциональны их массам.</p>',eq:`<div class="small">r₁ − R = ${frac('m₂','m₁ + m₂')}r</div><div class="small">r₂ − R = −${frac('m₁','m₁ + m₂')}r</div>`,note:'Чем тяжелее частица, тем меньше её отклонение относительно центра масс.'},
 {title:'Относительная частица',text:'<p>Теперь следим только за <strong>r = r₁ − r₂</strong>. Центр взаимодействия неподвижен; движется одна точка с приведённой массой μ. Плоскость движения задают входящая скорость и прицельный параметр.</p>',eq:`<div>μr̈ = −∇U(r)</div><div class="small">μ = ${frac('m₁m₂','m₁ + m₂')}, &nbsp; g = v₁ − v₂</div>`,note:'Прозрачная сфера: область исключения для относительного радиус-вектора; это не третья молекула.'}
]},
{tab:'Цилиндр',title:'Цилиндр<br>столкновений',kicker:'02 / ГЕОМЕТРИЯ ВСТРЕЧИ',scene:'Условие встречи записывается через центры',defaults:{model:'hs',b:.68,E:1,phi:26,time:.65},steps:[
 {title:'Сумма радиусов',text:'<p>Для встречи двух твёрдых сфер расстояние между их центрами должно уменьшиться до <strong>d = R₁ + R₂</strong>. Поэтому центр второй частицы должен попасть в трубку радиуса d вокруг свободного пути центра первой.</p>',eq:'<div>d = R₁ + R₂</div><div class="gold">b &lt; d &nbsp; ⇒ &nbsp; столкновение</div>',note:'Установите b > d: линия свободного пролёта больше не пересекает сферу исключения.'},
 {title:'Вид вдоль скорости',text:'<p>Посмотрите вдоль <strong>g</strong>. Длина цилиндра исчезает из проекции; остаётся круг допустимых положений центра второй частицы. Его площадь и есть полное сечение столкновения твёрдых сфер.</p>',eq:'<div class="gold">σ<sub>T</sub> = πd²</div><div class="small">= π(R₁ + R₂)²</div>',note:'Для одинаковых сфер радиуса R получается 4πR², а не πR².',view:'front'},
 {title:'Из площади в частоту встреч',text:'<p>За время Δt свободный относительный путь имеет длину gΔt. Объём цилиндра равен σ<sub>T</sub>gΔt. При однородной концентрации n₂ в нём в среднем находится n₂σ<sub>T</sub>gΔt центров частиц.</p>',eq:'<div>ΔV = σ<sub>T</sub>gΔt</div><div class="small">ν₁₂ = n₂σ<sub>T</sub>g</div>',note:'Здесь g фиксирована. Для газа с распределением скоростей усредняют произведение σ(g)g.'}
]},
{tab:'Прицельный b',title:'От прицельного<br>параметра к углу',kicker:'03 / ТВЁРДЫЕ СФЕРЫ',scene:'Линия центров определяет отражение',defaults:{model:'hs',b:.64,E:1,phi:0,time:.425},steps:[
 {title:'Прицельный параметр',text:'<p>Прицельный параметр <strong>b</strong>: расстояние от центра взаимодействия до входящей прямолинейной траектории. Он задан до сближения и не равен текущему расстоянию r между центрами.</p>',eq:'<div class="cyan">b = d sin β</div>',note:'Голубой отрезок измеряет b; радиус к точке контакта имеет длину d.'},
 {title:'Нормальная и касательная скорости',text:'<p>В точке касания нормальная составляющая относительной скорости меняет знак. Касательная сохраняется. Для упругих гладких сфер модуль g не меняется.</p>',eq:'<div class="small">g′ = g − 2(g · n)n</div><div class="small">|g′| = |g|</div>',note:'Нормаль n направлена от центра взаимодействия к точке контакта.'},
 {title:'Угол отклонения χ',text:'<p>Угол χ измеряется <strong>между направлениями g и g′</strong>, а не между двумя ветвями следа, обращёнными к точке контакта. Продолжение входящего направления показано пунктиром.</p>',eq:'<div>χ = π − 2β</div><div class="gold">b = d cos(χ/2)</div>',note:'Лобовой удар: b = 0, χ = π. Касательное прохождение: b → d, χ → 0.',view:'plane'}
]},
{tab:'Углы χ и φ',title:'Направление<br>в трёх измерениях',kicker:'04 / СФЕРА НАПРАВЛЕНИЙ',scene:'Один угол раскрывает конус, другой поворачивает плоскость',defaults:{model:'hs',b:.86,E:1,phi:38,time:.55},steps:[
 {title:'Полярный угол',text:'<p>При фиксированном b модуль отклонения χ уже определён. Но плоскость столкновения ещё можно поворачивать вокруг входящей скорости. Все возможные выходящие направления образуют конус.</p>',eq:'<div class="gold">cos χ = ĝ · ĝ′</div>',note:'Конус состоит из направлений скоростей; это не поверхность движения одной частицы.'},
 {title:'Азимут плоскости столкновения',text:'<p>Азимут <strong>φ</strong> отсчитывается в плоскости, перпендикулярной g, от +y к +z. При центральном потенциале изменение φ только поворачивает траекторию, не меняя χ.</p>',eq:'<div class="small">ĝ′ = (cos χ, sin χ cos φ, sin χ sin φ)</div>',note:'Перемещайте ползунок φ. Плоскость вращается, полярный угол остаётся прежним.'},
 {title:'Элемент телесного угла',text:'<p>На единичной сфере узкая ячейка имеет стороны dχ и sinχ dφ. Поэтому равные интервалы χ не имеют равных площадей: возле полюсов ячейки сжимаются.</p>',eq:'<div class="gold">dΩ = sinχ dχ dφ</div><div class="small">ΔΩ = Δφ (cos χ₁ − cos χ₂)</div>',note:'Жёлтая ячейка: конечный телесный угол. Её площадь делят на квадрат радиуса сферы.'}
]},
{tab:'Сечение',title:'Кольцо на входе.<br>Полоса направлений.',kicker:'05 / ДИФФЕРЕНЦИАЛЬНОЕ СЕЧЕНИЕ',scene:'Один и тот же поток, две разные меры',defaults:{model:'hs',b:.67,E:1,phi:18,width:.12,time:.66},steps:[
 {title:'Выбираем кольцо',text:'<p>Равномерный пучок освещает входную плоскость. Выделяем узкое кольцо прицельных параметров. Частиц через него проходит тем больше, чем больше его площадь, а не только ширина db.</p>',eq:'<div class="cyan">dσ = b db dφ</div><div class="small">dσ<sub>кольцо</sub> = 2πb db</div>',note:'Меняйте b при фиксированной ширине: внешнее кольцо пропускает больше частиц.'},
 {title:'Куда попадают те же частицы?',text:'<p>Каждому b соответствует χ(b), а азимут сохраняет ориентацию плоскости. Входное кольцо отображается в пояс на сфере направлений. Анимация показывает это соответствие, не пространственные траектории.</p>',eq:'<div class="gold">dΩ<sub>пояс</sub> = 2π sinχ |dχ|</div>',note:'Расширение или сжатие угловой полосы изменяет плотность потока на единицу телесного угла.'},
 {title:'Отношение площадей',text:'<p>Делим площадь входного кольца на телесный угол выходного пояса. Для твёрдых сфер отношение одинаково при любом b: рассеяние изотропно в системе центра масс.</p>',eq:`<div>${frac('dσ','dΩ')} = ${frac('b','sinχ')} |${frac('db','dχ')}|</div><div class="gold small">HS: &nbsp; ${frac('dσ','dΩ')} = ${frac('d²','4')}</div>`,note:'Изотропия означает постоянство по dΩ. Распределение по самому χ пропорционально sinχ.'}
]},
{tab:'Потенциалы',title:'Потенциал<br>задаёт траекторию',kicker:'06 / ДИНАМИКА СБЛИЖЕНИЯ',scene:'Положение, сила и энергия связаны с одним расчётом',defaults:{model:'lj',b:.75,E:1,phi:12,time:.46},steps:[
 {title:'От потенциала к силе',text:'<p>Точка на нижнем графике показывает текущее расстояние r. Сила направлена вдоль линии центров; её знак задаётся наклоном U(r). Переключайте потенциал, сохраняя одни и те же b и E.</p>',eq:`<div>F<sub>r</sub> = −${frac('dU','dr')}</div><div class="small">E = ½μg² &nbsp; при r → ∞</div>`,note:'Минимум потенциала соответствует нулевой силе, а не нулевой потенциальной энергии.'},
 {title:'Центробежный барьер',text:'<p>Момент количества движения <strong>L = μgb</strong> сохраняется. Радиальную часть движения можно рассматривать в эффективном потенциале. Наибольшее сближение достигается там, где радиальная скорость обращается в нуль.</p>',eq:`<div class="small">U<sub>eff</sub> = U(r) + ${frac('L²','2μr²')}</div><div class="small">½μṙ² + U<sub>eff</sub> = E</div>`,note:'При гладком отражении Ueff(rmin) = E; у твёрдого ядра отражение происходит на границе r = d.'},
 {title:'Одинаковые входные данные, разные силы',text:'<p>Степенное отталкивание только отклоняет частицу наружу. Потенциалы Сазерленда и Леннарда-Джонса сначала притягивают её. У Сазерленда есть твёрдое ядро; у LJ отталкивание гладкое.</p>',eq:'<div class="small">U<sub>LJ</sub> / ε = 4 [(ℓ₀/r)¹² − (ℓ₀/r)⁶]</div><div class="small">U<sub>IPL</sub> / ε = (ℓ₀/r)ⁿ</div>',note:'Сравнение приведённых потенциалов не является сравнением пяти моделей одного конкретного газа.',compare:true}
]},
{tab:'Функция χ(b)',title:'Траектория<br>и функция рассеяния',kicker:'07 / ОТ МЕХАНИКИ К СЕЧЕНИЮ',scene:'Выберите точку на графике: получите её траекторию',defaults:{model:'ipl',n:8,b:.85,E:1,phi:0,time:.6},steps:[
 {title:'Функция отклонения',text:'<p>Для каждого прицельного параметра решаем отдельную задачу движения. Из входящей и выходящей асимптот получаем угол. График снизу вычислен независимо от траектории: через радиальный интеграл.</p>',eq:`<div class="small">Θ = π − 2∫<sub>rmin</sub><sup>∞</sup> ${frac('b dr','r²√(1 − b²/r² − U/E)')}</div>`,note:'Щёлкните по графику Θ(b). Маркер и трёхмерная траектория относятся к одному b.'},
 {title:'Несколько b для одного направления',text:'<p>Притяжение допускает отрицательное отклонение Θ. Наблюдаемый угол равен χ = arccos(cos Θ). Разные прицельные параметры могут дать одно направление: их вклады в сечение нужно сложить.</p>',eq:`<div class="small">${frac('dσ','dΩ')} = ∑<sub>j</sub> ${frac('bⱼ','sinχ')} |${frac('dbⱼ','dχ')}|</div>`,note:'Вблизи экстремума Θ(b) возникает классическая радужная особенность. График сечения использует конечные угловые интервалы.',model:'lj',E:1.5,b:1.65},
 {title:'Неустойчивая круговая орбита',text:'<p>При энергии ниже максимума центробежного барьера есть критический прицельный параметр. Вблизи него частица долго задерживается возле неустойчивой круговой орбиты и может сделать несколько оборотов.</p>',eq:'<div class="small">U<sub>eff</sub>(r*) = E</div><div class="small">U′<sub>eff</sub>(r*) = 0, &nbsp; U″<sub>eff</sub>(r*) &lt; 0</div>',note:'Без диссипации это не устойчивый захват. В точности критическая траектория лишь асимптотически приближается к орбите.',model:'lj',E:.3,orbit:true}
]},
{tab:'Ансамбль',title:'От одного удара<br>к распределению',kicker:'08 / СТАТИСТИКА НАПРАВЛЕНИЙ',scene:'Равномерный входной поток не означает равномерный b',defaults:{model:'hs',b:.66,E:1,phi:22,width:.1,time:1,count:800},steps:[
 {title:'Равномерная выборка по площади',text:'<p>Чтобы получить однородный поток в диске, прицельный параметр нельзя выбирать равномерно. Внешние кольца имеют большую площадь. Случайный азимут независим от b.</p>',eq:'<div class="cyan">b = d√U₁</div><div class="small">φ = 2πU₂, &nbsp; U₁, U₂ ∼ U(0, 1)</div>',note:'Включите ошибочную выборку по b и сравните картину. Переизбыток лобовых ударов искажает распределение.'},
 {title:'Измеряем по равным телесным углам',text:'<p>На сфере накапливаются выходящие направления. Столбики ниже соответствуют равным интервалам cosχ, поэтому все интервалы имеют одинаковый телесный угол. Для HS средняя высота должна быть постоянной.</p>',eq:`<div class="small">ΔΩ = 2π Δ(cosχ)</div><div class="small">${frac('dσ','dΩ')} ≈ ${frac('πd²','N')} ${frac('Nₖ','ΔΩₖ')}</div>`,note:'Вертикальные штрихи: оценка статистического разброса счётчиков, а не погрешности модели.'},
 {title:'Сечение: мера потока',text:'<p>Облако частиц не заменяет сечение: оно даёт его статистическую оценку. Увеличивайте выборку. Интеграл гистограммы по телесному углу должен сохранять площадь входного пучка.</p>',eq:'<div class="gold">∑<sub>k</sub> (dσ/dΩ)<sub>k</sub> ΔΩ<sub>k</sub> = πd²</div>',note:'CSV сохраняет seed, входные параметры, направления и номера интервалов.'}
]},
{tab:'HS · VHS · VSS',title:'Что упрощает<br>модель DSMC',kicker:'09 / ЭФФЕКТИВНЫЕ МОДЕЛИ',scene:'Частота столкновений и распределение углов: разные свойства',defaults:{model:'hs',b:.66,E:1,phi:24,time:1,alpha:1.6,omega:.75,count:800,collisionModel:'hs'},steps:[
 {title:'HS: постоянное сечение',text:'<p>Модель твёрдых сфер задаёт постоянный эффективный диаметр. Рассеяние относительно центра масс изотропно. Это аналитический предельный случай, с которым удобно проверять алгоритм.</p>',eq:'<div>σ<sub>T</sub> = πd² = const</div><div class="small">cosχ = 2U − 1</div>',note:'На этой странице длины нормированы на dref, скорости: так, что gref = √2.',collisionModel:'hs'},
 {title:'VHS: диаметр зависит от скорости',text:'<p>У VHS диаметр изменяется с относительной скоростью. Это позволяет воспроизвести степенную температурную зависимость вязкости. Угловое распределение по-прежнему изотропно.</p>',eq:`<div class="small">${frac('d(g)','dref')} = (${frac('gref','g')})<sup>ω − ½</sup></div><div class="small">σ<sub>T</sub>(g) ∝ g<sup>1 − 2ω</sup></div>`,note:'При ω = ½ модель возвращается к постоянному диаметру HS.',collisionModel:'vhs'},
 {title:'VSS: отдельно настраиваем углы',text:'<p>У VSS параметр α меняет связь между прицельным параметром и углом, не меняя выбранное полное сечение. При α > 1 усиливается рассеяние вперёд. При α = 1 возвращаемся к VHS.</p>',eq:'<div class="small">cosχ = 2(b/d)<sup>2/α</sup> − 1</div><div class="small">= 2U<sup>1/α</sup> − 1</div>',note:'VHS и VSS здесь — модели сечения и закона рассеяния. Им не приписывается фиктивный потенциал U(r).',collisionModel:'vss'}
]}];

const CHAPTER_TEXT_EN=[
 {tab:'Two particles',title:'From two particles<br>to one motion',kicker:'01 / RELATIVE MOTION',scene:'What changes when the reference frame changes',steps:[
  {title:'Laboratory frame',text:'<p>Particle 1 hits particle 2, which was initially at rest. After the impact both particles move. Change the mass ratio: their paths change, but the law of relative motion stays the same.</p>',note:'Press play. The white center-of-mass marker moves uniformly.'},
  {title:'Center-of-mass frame',text:'<p>Subtract the center-of-mass velocity <strong>V</strong> from both velocities. The center of mass is now at rest. At every moment the particle radius vectors point in opposite directions and are inversely proportional to their masses.</p>',note:'The heavier the particle, the smaller its deflection relative to the center of mass.'},
  {title:'Relative particle',text:'<p>Now follow only <strong>r = r₁ − r₂</strong>. The interaction center is fixed; one point with reduced mass μ moves. The incoming velocity and impact parameter define the plane of motion.</p>',note:'The transparent sphere is the excluded region for the relative radius vector. It is not a third molecule.'}
 ]},
 {tab:'Cylinder',title:'The collision<br>cylinder',kicker:'02 / ENCOUNTER GEOMETRY',scene:'The encounter condition is written through the centers',steps:[
  {title:'Sum of radii',text:'<p>For two hard spheres to meet, the distance between their centers must fall to <strong>d = R₁ + R₂</strong>. The center of particle 2 must therefore enter a tube of radius d around the free path of the center of particle 1.</p>',note:'Set b > d: the free-flight line no longer crosses the excluded sphere.'},
  {title:'View along the velocity',text:'<p>Look along <strong>g</strong>. The cylinder length disappears from the projection; only a circle of allowed positions for the second center remains. Its area is the total collision cross section for hard spheres.</p>',note:'For equal spheres of radius R it is 4πR², not πR².'},
  {title:'From area to encounter rate',text:'<p>During Δt the free relative path has length gΔt. The cylinder volume is σ<sub>T</sub>gΔt. At uniform concentration n₂ it contains, on average, n₂σ<sub>T</sub>gΔt particle centers.</p>',note:'Here g is fixed. For a gas with a velocity distribution, average the product σ(g)g.'}
 ]},
 {tab:'Impact parameter b',title:'From impact<br>parameter to angle',kicker:'03 / HARD SPHERES',scene:'The line of centers determines the reflection',steps:[
  {title:'Impact parameter',text:'<p>The impact parameter <strong>b</strong> is the distance from the interaction center to the incoming straight-line path. It is set before the approach and is not the current center-to-center distance r.</p>',note:'The blue segment measures b; the radius to the contact point has length d.'},
  {title:'Normal and tangential velocity',text:'<p>At contact, the normal component of the relative velocity reverses sign. The tangential component is preserved. For smooth elastic spheres the magnitude of g is unchanged.</p>',note:'The normal n points from the interaction center to the contact point.'},
  {title:'Deflection angle χ',text:'<p>The angle χ is measured <strong>between the directions of g and g′</strong>, not between the two trail branches that point toward the contact point. The continuation of the incoming direction is shown dashed.</p>',note:'Head-on impact: b = 0, χ = π. Tangential passage: b → d, χ → 0.'}
 ]},
 {tab:'Angles χ and φ',title:'Direction<br>in three dimensions',kicker:'04 / DIRECTION SPHERE',scene:'One angle opens a cone, the other rotates its plane',steps:[
  {title:'Polar angle',text:'<p>For fixed b, the deflection magnitude χ is already determined. But the collision plane can still rotate around the incoming velocity. All possible outgoing directions form a cone.</p>',note:'The cone consists of velocity directions. It is not the path surface of one particle.'},
  {title:'Azimuth of the collision plane',text:'<p>The azimuth <strong>φ</strong> is measured in the plane perpendicular to g, from +y toward +z. For a central potential, changing φ only rotates the trajectory and does not change χ.</p>',note:'Move the φ slider. The plane rotates while the polar angle stays unchanged.'},
  {title:'Solid-angle element',text:'<p>On a unit sphere, a narrow cell has sides dχ and sinχ dφ. Equal χ intervals therefore do not have equal areas: cells contract near the poles.</p>',note:'The yellow cell is a finite solid angle. Divide its area by the square of the sphere radius.'}
 ]},
 {tab:'Cross section',title:'A ring at input.<br>A band of directions.',kicker:'05 / DIFFERENTIAL CROSS SECTION',scene:'The same flux, two different measures',steps:[
  {title:'Choose a ring',text:'<p>A uniform beam illuminates the input plane. Select a narrow ring of impact parameters. The number of particles passing through it grows with its area, not just with its width db.</p>',note:'Change b at fixed width: the outer ring passes more particles.'},
  {title:'Where do the same particles go?',text:'<p>Each b corresponds to χ(b), while the azimuth preserves the orientation of the plane. The input ring maps to a band on the direction sphere. The animation shows this correspondence, not spatial trajectories.</p>',note:'Widening or narrowing the angular band changes the flux density per unit solid angle.'},
  {title:'Ratio of areas',text:'<p>Divide the input-ring area by the solid angle of the output band. For hard spheres the ratio is the same for every b: scattering is isotropic in the center-of-mass frame.</p>',note:'Isotropy means constant per dΩ. The distribution in χ itself is proportional to sinχ.'}
 ]},
 {tab:'Potentials',title:'The potential<br>sets the trajectory',kicker:'06 / APPROACH DYNAMICS',scene:'Position, force, and energy come from one calculation',steps:[
  {title:'From potential to force',text:'<p>The point on the lower graph shows the current distance r. The force acts along the line of centers; its sign is set by the slope of U(r). Switch potentials while keeping the same b and E.</p>',note:'A potential minimum means zero force, not zero potential energy.'},
  {title:'Centrifugal barrier',text:'<p>Angular momentum <strong>L = μgb</strong> is conserved. The radial motion can be viewed in an effective potential. The closest approach occurs where the radial velocity becomes zero.</p>',note:'For smooth reflection Ueff(rmin) = E. For a hard core, reflection occurs at r = d.'},
  {title:'Same input, different forces',text:'<p>Power-law repulsion only deflects the particle outward. Sutherland and Lennard-Jones potentials first attract it. Sutherland has a hard core; LJ has smooth repulsion.</p>',note:'Comparing reduced potentials is not a comparison of five models for one particular gas.'}
 ]},
 {tab:'Function χ(b)',title:'Trajectory<br>and scattering function',kicker:'07 / FROM MECHANICS TO CROSS SECTION',scene:'Choose a graph point and get its trajectory',steps:[
  {title:'Deflection function',text:'<p>We solve a separate motion problem for each impact parameter. The angle comes from the incoming and outgoing asymptotes. The lower graph is computed independently through the radial integral.</p>',note:'Click the Θ(b) graph. The marker and the three-dimensional trajectory use the same b.'},
  {title:'Several b values for one direction',text:'<p>Attraction allows negative deflection Θ. The observed angle is χ = arccos(cos Θ). Different impact parameters can produce one direction, so their cross-section contributions must be added.</p>',note:'Near an extremum of Θ(b), a classical rainbow feature appears. The cross-section graph uses finite angular intervals.'},
  {title:'Unstable circular orbit',text:'<p>Below the centrifugal-barrier maximum there is a critical impact parameter. Near it, the particle lingers around an unstable circular orbit and may make several turns.</p>',note:'Without dissipation this is not stable capture. Exactly at the critical trajectory, the orbit is approached only asymptotically.'}
 ]},
 {tab:'Ensemble',title:'From one impact<br>to a distribution',kicker:'08 / DIRECTION STATISTICS',scene:'A uniform incoming flux does not mean a uniform b',steps:[
  {title:'Uniform sampling by area',text:'<p>To obtain a uniform flux in a disk, the impact parameter cannot be sampled uniformly. Outer rings have more area. A random azimuth is independent of b.</p>',note:'Enable incorrect sampling by b and compare the pattern. Too many head-on impacts distort the distribution.'},
  {title:'Measure by equal solid angles',text:'<p>Outgoing directions accumulate on the sphere. The bars below use equal cosχ intervals, so every interval has the same solid angle. For HS the mean height should be constant.</p>',note:'Vertical marks estimate statistical counting scatter, not model error.'},
  {title:'Cross section as a flux measure',text:'<p>A particle cloud does not replace a cross section; it gives a statistical estimate. Increase the sample. The histogram integral over solid angle should preserve the input-beam area.</p>',note:'CSV stores the seed, input parameters, directions, and bin numbers.'}
 ]},
 {tab:'HS · VHS · VSS',title:'What the DSMC<br>model simplifies',kicker:'09 / EFFECTIVE MODELS',scene:'Collision rate and angular distribution are different properties',steps:[
  {title:'HS: constant cross section',text:'<p>The hard-sphere model uses a constant effective diameter. Scattering in the center-of-mass frame is isotropic. This analytic limiting case is useful for checking the algorithm.</p>',note:'Lengths are normalized by dref and velocities by gref = √2 on this page.'},
  {title:'VHS: diameter depends on speed',text:'<p>For VHS, the diameter changes with relative speed. This reproduces a power-law temperature dependence of viscosity. The angular distribution remains isotropic.</p>',note:'At ω = ½ the model returns to the constant-diameter HS case.'},
  {title:'VSS: tune the angles separately',text:'<p>For VSS, the parameter α changes the relation between impact parameter and angle without changing the chosen total cross section. At α > 1 forward scattering is stronger. At α = 1 we return to VHS.</p>',note:'VHS and VSS here are models for cross section and scattering law. No fictitious potential U(r) is assigned to them.'}
 ]}
];

const CHAPTER_TEXT_RU=CHAPTERS.map(chapter=>({tab:chapter.tab,title:chapter.title,kicker:chapter.kicker,scene:chapter.scene,steps:chapter.steps.map(step=>({title:step.title,text:step.text,note:step.note}))}));

export function setChapterLanguage(locale){
 const text=locale==='en'?CHAPTER_TEXT_EN:CHAPTER_TEXT_RU;
 CHAPTERS.forEach((chapter,index)=>{
  const source=text[index];
  for(const key of ['tab','title','kicker','scene']) chapter[key]=source[key];
  chapter.steps.forEach((step,stepIndex)=>{
   for(const key of ['title','text','note']) step[key]=source.steps[stepIndex][key];
  });
 });
}
